server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: oauth2-client
  mvc:
    # 必须添加否则swagger2会报错
    pathmatch:
      matching-strategy: ant_path_matcher
captcha:
  enabled: false
  border: false
  width: 130
  height: 48
  font-size: 30
  char-length: 4
  font: 微软雅黑
  expireSeconds: 60


login:
  uri: /login

logout:
  uri: /logout

token:
  access-token-expire-minutes: 30
  refresh-token-expire-minutes: 3000

# swagger-bootstrap-ui
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: bty
    password: 123456
