spring:
  profiles:
    active: dev


captcha:
  enabled: false
  border: false
  width: 130
  height: 48
  font-size: 30
  char-length: 4
  font: 微软雅黑
  expireSeconds: 60


login:
  uri: /login

logout:
  uri: /logout
