server:
  port: 8080
token:
  expire-minutes: 30
  secret: dfjsfer2334re2342fdsx.



spring:

  mvc:
    # 必须添加否则swagger2会报错
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
  security:

    oauth2:
      client:
        registration:
          gitee:
            provider: gitee
            authorization-grant-type: authorization_code
            scope:
              - user_info
              - emails
              - projects
            client-id: 6daaa0856139bddf4aed00896ba6a62be8df4994401e95a2de2f9563f9c1062b
            client-secret: e88ca1d2519ecd39c263cc10f089e65d86712d7cfce9657249495529231014fb
            # 默认pattern /login/oauth2/code/{registration_id}
            redirect-uri: http://localhost:8080/login/oauth2/code/gitee
            client-name: gitee
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            # 注意，这里的user-name-attribute指的是每个平台用户名的key的名字，每个平台不一样的，gitee是name，所以这里写name
            user-name-attribute: name
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: bty
    password: 123456

