server:
  port: 8080
token:
  access-token-expire-minutes: 30
  refresh-token-expire-minutes: 3000
  secret: dfjsfer2334re2342fdsx.



spring:
  mvc:
    # 必须添加否则swagger2会报错
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
  security:
    oauth2:
      client:
        registration:
          # google facebook github okta的provider默认提供
          # 参见 org.springframework.security.config.oauth2.client.CommonOAuth2Provider
          google:
            authorization-grant-type: authorization_code

            scope:
              - openid
              - profile
            client-id: 1002538069997-86b2snre376ljmtt2efcgntai9pf3pkk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          gitee:
            provider: gitee
            authorization-grant-type: authorization_code
            scope:
              - user_info
              - emails
            client-id: 6daaa0856139bddf4aed00896ba6a62be8df4994401e95a2de2f9563f9c1062b
            client-secret: cfaae87e9b239858aba809f3584973eb81bd383c5814a3fb899a9caf065fdf81

            # 这儿是把code传到前端，前端再把code和state参数给后端
            # 这里填写的是前端的地址，后端Spring Security接受code默认pattern /login/oauth2/code/{registration_id}
            redirect-uri: http://localhost:8080/login/oauth2/code/gitee
            client-name: gitee
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            # 注意，这里的user-name-attribute指的是每个平台用户名的key的名字，每个平台不一样的，gitee是name，所以这里写name
            user-name-attribute: name
# swagger-bootstrap-ui
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: bty
    password: 123456
